# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

      

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    env:
      JWT_SECRET: "fakepsw"

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install
    - run: npm run cy/backend
    
    - name: Send Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: e05
        SLACK_COLOR: "#9e2a2b"
        SLACK_ICON: https://cdn-icons-png.flaticon.com/512/25/25231.png
        SLACK_MESSAGE: "Failed tests"
        SLACK_TITLE: Failed execution
        SLACK_USERNAME: Test Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Send Slack Notification on successful tests
      if: ${{ !failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: e05
        SLACK_COLOR: "#7CFC00"
        SLACK_ICON: https://cdn-icons-png.flaticon.com/512/25/25231.png
        SLACK_MESSAGE: "Successful tests"
        SLACK_TITLE: Successful tests
        SLACK_USERNAME: Test Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      
